// InputActions.cs — STUB
// ─────────────────────────────────────────────────────────────────────────────
// Normally this file is auto-generated by Unity's Input System package from an
// .inputactions asset. This stub lets the project compile without that asset.
//
// TO REPLACE THIS STUB:
//   1. In the Project window, right-click → Create → Input Actions
//   2. Name it "InputActions" and add a Player action map with these actions:
//      Menu, PlayerLeft, PlayerRight, PlayerUp, PlayerDown,
//      Attack, Skill, Special, PlayerDash, PlayerJump
//   3. In the asset's Inspector, enable "Generate C# Class" and click Apply.
//   4. Delete this file once the generated class appears.
// ─────────────────────────────────────────────────────────────────────────────

using UnityEngine.InputSystem;

public class InputActions
{
    public PlayerActions Player { get; } = new PlayerActions();

    public void Enable()  => Player.Enable();
    public void Disable() => Player.Disable();

    public class PlayerActions
    {
        public InputAction Menu        = new InputAction("Menu",        InputActionType.Button);
        public InputAction PlayerLeft  = new InputAction("PlayerLeft",  InputActionType.Button);
        public InputAction PlayerRight = new InputAction("PlayerRight", InputActionType.Button);
        public InputAction PlayerUp    = new InputAction("PlayerUp",    InputActionType.Button);
        public InputAction PlayerDown  = new InputAction("PlayerDown",  InputActionType.Button);
        public InputAction Attack      = new InputAction("Attack",      InputActionType.Button);
        public InputAction Skill       = new InputAction("Skill",       InputActionType.Button);
        public InputAction Special     = new InputAction("Special",     InputActionType.Button);
        public InputAction PlayerDash  = new InputAction("PlayerDash",  InputActionType.Button);
        public InputAction PlayerJump  = new InputAction("PlayerJump",  InputActionType.Button);

        public void Enable()
        {
            Menu.Enable();        PlayerLeft.Enable();  PlayerRight.Enable();
            PlayerUp.Enable();    PlayerDown.Enable();  Attack.Enable();
            Skill.Enable();       Special.Enable();     PlayerDash.Enable();
            PlayerJump.Enable();
        }

        public void Disable()
        {
            Menu.Disable();       PlayerLeft.Disable();  PlayerRight.Disable();
            PlayerUp.Disable();   PlayerDown.Disable();  Attack.Disable();
            Skill.Disable();      Special.Disable();     PlayerDash.Disable();
            PlayerJump.Disable();
        }
    }
}
